spring.application.name=bai1

spring.datasource.url=jdbc:mysql://localhost:3306/Session10_MD4?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=86400000


cloudinary.cloud-name=dg2ouh6uu
cloudinary.api-key=449739856393812
cloudinary.api-secret=ZeytpkUJPwXcBxDaNGQVQHBFRSg


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ptnan1997@gmail.com
spring.mail.password=Ngoc@n1997

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true